version: '3.8'

services:
  backend:
    build: ../backend
    ports:
      - "5000:5000"
    volumes:
      - ../backend:/app
      - /app/instance

  frontend:
    build: ../frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
