"""Add shipping address to Order model

Revision ID: ca9195bacc01
Revises: 47c59b362bad
Create Date: 2025-08-08 05:39:36.372957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca9195bacc01'
down_revision = '47c59b362bad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_address', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('shipping_city', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('shipping_postal_code', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('shipping_country', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('shipping_country')
        batch_op.drop_column('shipping_postal_code')
        batch_op.drop_column('shipping_city')
        batch_op.drop_column('shipping_address')

    # ### end Alembic commands ###
